"""
Prometheus metrics definitions.

All metrics are module-level singletons (standard Prometheus pattern).
Import and use them anywhere in the codebase.
"""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, Summary

# ── Trading metrics ────────────────────────────────────────────────────────

TRADING_SIGNALS = Counter(
    "trading_signals_total",
    "Number of signals generated by strategy",
    ["symbol", "action"],
)

TRADES_TOTAL = Counter(
    "trades_total",
    "Total number of completed trades",
    ["symbol", "mode"],
)

TRADE_PNL = Histogram(
    "trade_pnl_usdt",
    "PnL per trade in USDT",
    ["symbol", "mode"],
    buckets=[-500, -200, -100, -50, -20, -10, 0, 10, 20, 50, 100, 200, 500],
)

PORTFOLIO_EQUITY = Gauge(
    "portfolio_equity_usdt",
    "Current portfolio equity in USDT",
    ["mode"],
)

DAILY_PNL = Gauge(
    "daily_pnl_usdt",
    "Cumulative daily PnL in USDT",
    ["mode"],
)

DAILY_DRAWDOWN_PCT = Gauge(
    "daily_drawdown_pct",
    "Current daily drawdown percentage",
    ["mode"],
)

OPEN_POSITIONS = Gauge(
    "open_positions",
    "Number of currently open positions",
    ["symbol", "mode"],
)

# ── Data feed metrics ────────────────────────────────────────────────────────

DATA_FEED_DELAY_SECONDS = Gauge(
    "data_feed_delay_seconds",
    "Age of the latest market data bar in seconds",
    ["symbol", "timeframe"],
)

CANDLES_INGESTED = Counter(
    "candles_ingested_total",
    "Total OHLCV candles ingested from exchange",
    ["symbol", "timeframe"],
)

# ── API / broker metrics ─────────────────────────────────────────────────────

BROKER_API_REQUESTS = Counter(
    "broker_api_requests_total",
    "Total API requests to broker",
    ["endpoint", "status"],
)

BROKER_API_LATENCY = Histogram(
    "broker_api_latency_seconds",
    "Broker API call latency",
    ["endpoint"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 5.0],
)

BROKER_API_ERRORS = Counter(
    "broker_api_errors_total",
    "Total broker API errors",
    ["error_type"],
)

# ── Risk metrics ─────────────────────────────────────────────────────────────

KILL_SWITCH_TRIGGERS = Counter(
    "kill_switch_triggers_total",
    "Number of times kill switch has been triggered",
    ["reason"],
)

RISK_VIOLATIONS = Counter(
    "risk_violations_total",
    "Number of signals rejected by risk manager",
    ["reason"],
)

# ── System metrics ───────────────────────────────────────────────────────────

BOT_HEARTBEAT = Gauge(
    "bot_heartbeat_timestamp",
    "Unix timestamp of last bot heartbeat",
    ["mode"],
)

CELERY_TASKS_RUNNING = Gauge(
    "celery_tasks_running",
    "Number of currently running Celery tasks",
    ["task_name"],
)

BACKTEST_RUNS_TOTAL = Counter(
    "backtest_runs_total",
    "Total number of backtest runs",
    ["strategy", "status"],
)
